<select id="city-id-select-" class="light br3 required long x-normal city-select default">
    <option value="">Choose</option>
</select>
<select id="city-id-select-2" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1793">Boliney</option>
    <option value="1794">Bucay</option>
    <option value="1795">Bucloc</option>
    <option value="1796">Dolores</option>
    <option value="1797">Lacub</option>
    <option value="1798">Lagangilang</option>
    <option value="1799">Luba</option>
    <option value="1800">Malibcong</option>
    <option value="1801">Manabo</option>
    <option value="1802">Pidigan</option>
    <option value="1803">Pilar</option>
    <option value="1804">Sallapadan</option>
    <option value="1805">San Isidro</option>
    <option value="1806">Tayum</option>
    <option value="1807">Tineg</option>
    <option value="1808">Villaviciosa</option>
    <option value="18">Bangued</option>
    <option value="22">Daguioman</option>
    <option value="23">Danglas</option>
    <option value="25">La Paz</option>
    <option value="28">Lagayan</option>
    <option value="29">Langiden</option>
    <option value="30">Licuan-Baay</option>
    <option value="34">Peñarrubia</option>
    <option value="39">San Juan</option>
    <option value="40">San Quintin</option>
    <option value="43">Tubo</option>
</select>
<select id="city-id-select-3" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1809">Calanasan (Bayag)</option>
    <option value="1810">Flora</option>
    <option value="1811">Santa Marcela</option>
    <option value="47">Conner</option>
    <option value="49">Kabugao</option>
    <option value="50">Luna</option>
    <option value="51">Pudtol</option>
</select>
<select id="city-id-select-5" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1812">Tinoc</option>
    <option value="69">Aguinaldo</option>
    <option value="70">Alfonso Lista</option>
    <option value="71">Asipulo</option>
    <option value="72">Banaue</option>
    <option value="73">Hingyon</option>
    <option value="74">Hungduan</option>
    <option value="75">Kiangan</option>
    <option value="76">Lagawe</option>
    <option value="77">Lamut</option>
    <option value="78">Mayoyao</option>
</select>
<select id="city-id-select-1" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1">Manila</option>
    <option value="2">Caloocan</option>
    <option value="3">Pasay</option>
    <option value="4">Quezon City</option>
    <option value="5">Las Piñas</option>
    <option value="6">Makati</option>
    <option value="7">Malabon</option>
    <option value="8">Mandaluyong</option>
    <option value="9">Marikina</option>
    <option value="10">Muntinlupa</option>
    <option value="11">Navotas</option>
    <option value="12">Parañaque</option>
    <option value="13">Pasig</option>
    <option value="16">Valenzuela</option>
    <option value="1590">Pateros</option>
    <option value="1788">San Juan</option>
    <option value="1789">Taguig</option>
</select>
<select id="city-id-select-4" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="54">Atok</option>
    <option value="55">Baguio</option>
    <option value="56">Bakun</option>
    <option value="57">Bokod</option>
    <option value="58">Buguias</option>
    <option value="59">Itogon</option>
    <option value="60">Kabayan</option>
    <option value="61">Kapangan</option>
    <option value="62">Kibungan</option>
    <option value="63">La Trinidad</option>
    <option value="64">Mankayan</option>
    <option value="65">Sablan</option>
    <option value="66">Tuba</option>
    <option value="67">Tublay</option>
</select>
<select id="city-id-select-6" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="81">Balbalan</option>
    <option value="82">Lubuagan</option>
    <option value="83">Pasil</option>
    <option value="84">Pinukpuk</option>
    <option value="85">Rizal</option>
    <option value="86">Tabuk</option>
    <option value="87">Tanudan</option>
    <option value="88">Tinglayan</option>
</select>
<select id="city-id-select-7" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="90">Barlig</option>
    <option value="91">Bauko</option>
    <option value="92">Besao</option>
    <option value="93">Bontoc</option>
    <option value="94">Natonin</option>
    <option value="95">Paracelis</option>
    <option value="96">Sabangan</option>
    <option value="97">Sadanga</option>
    <option value="98">Sagada</option>
    <option value="99">Tadian</option>
</select>
<select id="city-id-select-8" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="101">Adams</option>
    <option value="102">Bacarra</option>
    <option value="103">Badoc</option>
    <option value="104">Bangui</option>
    <option value="105">Banna</option>
    <option value="106">Burgos</option>
    <option value="107">Carasi</option>
    <option value="108">Currimao</option>
    <option value="109">Dingras</option>
    <option value="110">Dumalneg</option>
    <option value="111">Laoag City</option>
    <option value="112">Marcos</option>
    <option value="113">Nueva Era</option>
    <option value="114">Pagudpud</option>
    <option value="115">Paoay</option>
    <option value="116">Pasuquin</option>
    <option value="117">Piddig</option>
    <option value="118">Pinili</option>
    <option value="119">San Nicolas</option>
    <option value="120">Sarrat</option>
    <option value="121">Solsona</option>
    <option value="122">Vintar</option>
    <option value="1591">Batac City</option>
</select>
<select id="city-id-select-9" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="124">Alilem</option>
    <option value="125">Banayoyo</option>
    <option value="126">Bantay</option>
    <option value="127">Burgos</option>
    <option value="128">Cabugao</option>
    <option value="129">Caoayan</option>
    <option value="130">Cervantes</option>
    <option value="131">Galimuyod</option>
    <option value="132">Gregorio Del Pilar</option>
    <option value="133">Lidlidda</option>
    <option value="134">Magsingal</option>
    <option value="135">Nagbukel</option>
    <option value="136">Narvacan</option>
    <option value="137">Quirino</option>
    <option value="138">Salcedo</option>
    <option value="139">San Emilio</option>
    <option value="140">San Esteban</option>
    <option value="141">San Ildefonso</option>
    <option value="142">San Juan</option>
    <option value="143">San Vicente</option>
    <option value="144">Santa</option>
    <option value="145">Santa Catalina</option>
    <option value="146">Santa Cruz</option>
    <option value="147">Santa Lucia</option>
    <option value="148">Santa Maria</option>
    <option value="149">Santiago</option>
    <option value="150">Santo Domingo</option>
    <option value="151">Sigay</option>
    <option value="152">Sinait</option>
    <option value="153">Sugpon</option>
    <option value="154">Suyo</option>
    <option value="155">Tagudin</option>
    <option value="1592">Candon City</option>
    <option value="1593">Vigan City</option>
</select>
<select id="city-id-select-10" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="157">Agoo</option>
    <option value="158">Aringay</option>
    <option value="159">Bacnotan</option>
    <option value="160">Bagulin</option>
    <option value="161">Balaoan</option>
    <option value="162">Bangar</option>
    <option value="163">Bauang</option>
    <option value="164">Burgos</option>
    <option value="165">Caba</option>
    <option value="166">Luna</option>
    <option value="167">Naguilian</option>
    <option value="168">Pugo</option>
    <option value="169">Rosario</option>
    <option value="170">San Fernando City</option>
    <option value="171">San Gabriel</option>
    <option value="172">San Juan</option>
    <option value="173">Santo Tomas</option>
    <option value="174">Santol</option>
    <option value="175">Sudipen</option>
    <option value="176">Tubao</option>
</select>
<select id="city-id-select-11" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="178">Agno</option>
    <option value="179">Aguilar</option>
    <option value="180">Alcala</option>
    <option value="181">Anda</option>
    <option value="182">Asingan</option>
    <option value="183">Balungao</option>
    <option value="184">Bani</option>
    <option value="185">Basista</option>
    <option value="186">Bautista</option>
    <option value="187">Bayambang</option>
    <option value="188">Binalonan</option>
    <option value="189">Binmaley</option>
    <option value="190">Bolinao</option>
    <option value="191">Bugallon</option>
    <option value="192">Burgos</option>
    <option value="193">Calasiao</option>
    <option value="194">Dasol</option>
    <option value="195">Mangatarem</option>
    <option value="196">Infanta</option>
    <option value="197">Labrador</option>
    <option value="198">Laoac</option>
    <option value="199">Lingayen</option>
    <option value="200">Mabini</option>
    <option value="201">Malasiqu</option>
    <option value="202">Manaoag</option>
    <option value="203">Mangaldan</option>
    <option value="205">Mapandan</option>
    <option value="206">Natividad</option>
    <option value="207">Pozorrubio</option>
    <option value="208">Rosales</option>
    <option value="1594">Alaminos</option>
    <option value="1595">Dagupan City</option>
    <option value="1596">San Carlos City</option>
    <option value="1597">San Fabian</option>
    <option value="1598">San Jacinto</option>
    <option value="1599">San Manuel</option>
    <option value="1600">San Nicolas</option>
    <option value="1601">San Quintin</option>
    <option value="1602">Santa Barbara</option>
    <option value="1603">Santa Maria</option>
    <option value="1604">Santo Tomas</option>
    <option value="1605">Sison</option>
    <option value="1606">Sual</option>
    <option value="1607">Tayug</option>
    <option value="1608">Umingan</option>
    <option value="1609">Urbiztondo</option>
    <option value="1610">Urdaneta City</option>
    <option value="1611">Villasis</option>
</select>
<select id="city-id-select-12" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="210">Basco</option>
    <option value="211">Itbayat</option>
    <option value="212">Ivana</option>
    <option value="213">Mahatao</option>
    <option value="214">Sabtang</option>
    <option value="215">Uyugan</option>
</select>
<select id="city-id-select-13" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="217">Abulug</option>
    <option value="218">Alcala</option>
    <option value="219">Allacapan</option>
    <option value="220">Amulung</option>
    <option value="221">Aparri</option>
    <option value="222">Baggao</option>
    <option value="223">Ballesteros</option>
    <option value="224">Buguey</option>
    <option value="225">Calayan</option>
    <option value="226">Camalaniugan</option>
    <option value="227">Claveria</option>
    <option value="228">Enrile</option>
    <option value="229">Gattaran</option>
    <option value="230">Gonzaga</option>
    <option value="231">Iguig</option>
    <option value="232">Lal-Lo</option>
    <option value="233">Lasam</option>
    <option value="234">Pamplona</option>
    <option value="235">Peñablanca</option>
    <option value="236">Piat</option>
    <option value="237">Rizal</option>
    <option value="238">Sanchez-Mira</option>
    <option value="239">Santa Ana</option>
    <option value="240">Santa Praxedes</option>
    <option value="241">Santa Teresita</option>
    <option value="242">Santo Niño (Faire)</option>
    <option value="243">Solana</option>
    <option value="244">Tuao</option>
    <option value="1612">Tuguegarao City</option>
</select>
<select id="city-id-select-14" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="246">Angadanan</option>
    <option value="247">Aurora</option>
    <option value="248">Benito Soliven</option>
    <option value="249">Burgos</option>
    <option value="250">Cabagan</option>
    <option value="251">Cabatuan</option>
    <option value="252">Cauayan City</option>
    <option value="253">Cordon</option>
    <option value="254">Delfin Albano</option>
    <option value="255">Dinapigue</option>
    <option value="256">Divilacan</option>
    <option value="257">Echague</option>
    <option value="258">Gamu</option>
    <option value="259">Ilagan City</option>
    <option value="260">Jones</option>
    <option value="261">Luna</option>
    <option value="262">Maconacon</option>
    <option value="263">Mallig</option>
    <option value="264">Naguilian</option>
    <option value="265">Palanan</option>
    <option value="266">Quezon</option>
    <option value="267">Quirino</option>
    <option value="268">Ramon</option>
    <option value="269">Reina Mercedes</option>
    <option value="270">Roxas</option>
    <option value="271">San Agustin</option>
    <option value="272">San Guillermo</option>
    <option value="273">San Isidro</option>
    <option value="274">San Manuel</option>
    <option value="275">San Mariano</option>
    <option value="276">San Mateo</option>
    <option value="277">San Pablo</option>
    <option value="278">Santa Maria</option>
    <option value="279">Santiago City</option>
    <option value="280">Santo Tomas</option>
    <option value="281">Tumauini</option>
    <option value="1613">Alicia</option>
</select>
<select id="city-id-select-15" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="283">Alfonso Castañeda</option>
    <option value="284">Ambaguio</option>
    <option value="285">Aritao</option>
    <option value="286">Bagabag</option>
    <option value="287">Bambang</option>
    <option value="288">Bayombong</option>
    <option value="289">Diadi</option>
    <option value="290">Dupax Del Norte</option>
    <option value="291">Dupax Del Sur</option>
    <option value="293">Kayapa</option>
    <option value="294">Quezon</option>
    <option value="295">Santa Fe</option>
    <option value="296">Solano</option>
    <option value="297">Villaverde</option>
    <option value="1614">Kasibu</option>
</select>
<select id="city-id-select-16" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="299">Aglipay</option>
    <option value="300">Cabarroguis</option>
    <option value="301">Diffun</option>
    <option value="302">Maddela</option>
    <option value="303">Nagtipunan</option>
    <option value="304">Saguday</option>
</select>
<select id="city-id-select-17" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="306">Baler</option>
    <option value="307">Casiguran</option>
    <option value="308">Dilasag</option>
    <option value="309">Dinalungan</option>
    <option value="310">Dingalan</option>
    <option value="311">Dipaculao</option>
    <option value="312">Maria Aurora</option>
    <option value="313">San Luis</option>
</select>
<select id="city-id-select-18" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="315">Abucay</option>
    <option value="316">Bagac</option>
    <option value="317">Dinalupihan</option>
    <option value="318">Hermosa</option>
    <option value="319">Limay</option>
    <option value="320">Mariveles</option>
    <option value="321">Morong</option>
    <option value="322">Orani</option>
    <option value="323">Orion</option>
    <option value="324">Pilar</option>
    <option value="325">Samal</option>
    <option value="1615">Balanga City</option>
</select>
<select id="city-id-select-19" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="327">Angat</option>
    <option value="328">Balagtas</option>
    <option value="329">Baliuag</option>
    <option value="330">Bocaue</option>
    <option value="331">Bulakan</option>
    <option value="332">Bustos</option>
    <option value="333">Calumpit</option>
    <option value="334">Doña Remedios Trinidad</option>
    <option value="335">Guiguinto</option>
    <option value="336">Hagonoy</option>
    <option value="337">Malolos City</option>
    <option value="338">Marilao</option>
    <option value="339">Meycauayan City</option>
    <option value="340">Norzagaray</option>
    <option value="341">Obando</option>
    <option value="342">Pandi</option>
    <option value="343">Paombong</option>
    <option value="344">Plaridel</option>
    <option value="345">Pulilan</option>
    <option value="346">San Ildefonso</option>
    <option value="347">San Jose del Monte</option>
    <option value="348">San Miguel</option>
    <option value="349">San Rafael</option>
    <option value="350">Santa Maria</option>
</select>
<select id="city-id-select-20" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="352">Aliaga</option>
    <option value="353">Bongabon</option>
    <option value="354">Cabiao</option>
    <option value="355">Carranglan</option>
    <option value="356">Cuyapo</option>
    <option value="357">Gabaldon</option>
    <option value="358">General Mamerto Natividad</option>
    <option value="359">General Tinio</option>
    <option value="360">Guimba</option>
    <option value="361">Jaen</option>
    <option value="362">Laur</option>
    <option value="363">Licab</option>
    <option value="364">Llanera</option>
    <option value="365">Lupao</option>
    <option value="366">Nampicuan</option>
    <option value="367">Pantabangan</option>
    <option value="368">Peñaranda</option>
    <option value="369">Quezon</option>
    <option value="370">Rizal</option>
    <option value="371">San Antonio</option>
    <option value="372">San Isidro</option>
    <option value="373">San Leonardo</option>
    <option value="374">Santa Rosa</option>
    <option value="375">Santo Domingo</option>
    <option value="376">Talavera</option>
    <option value="377">Talugtug</option>
    <option value="378">Zaragoza</option>
    <option value="1616">Cabanatuan City</option>
    <option value="1617">Gapan City</option>
    <option value="1618">Munoz City</option>
    <option value="1619">Palayan City</option>
    <option value="1620">San Jose City</option>
</select>
<select id="city-id-select-21" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="380">Angeles City</option>
    <option value="381">San Fernando</option>
    <option value="382">Mabalacat</option>
    <option value="383">Apalit</option>
    <option value="384">Arayat</option>
    <option value="385">Bacolor</option>
    <option value="386">Candaba</option>
    <option value="387">Floridablanca</option>
    <option value="388">Guagua</option>
    <option value="389">Lubao</option>
    <option value="390">Macabebe</option>
    <option value="391">Magalang</option>
    <option value="392">Masantol</option>
    <option value="393">Mexico</option>
    <option value="394">Minalin</option>
    <option value="395">Porac</option>
    <option value="396">San Luis</option>
    <option value="397">San Simon</option>
    <option value="398">Santa Ana</option>
    <option value="399">Santa Rita</option>
    <option value="400">Santo Tomas</option>
    <option value="401">Sasmuan</option>
</select>
<select id="city-id-select-22" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="403">Anao</option>
    <option value="404">Bamban</option>
    <option value="405">Camiling</option>
    <option value="406">Capas</option>
    <option value="407">Concepcion</option>
    <option value="408">Gerona</option>
    <option value="409">La Paz</option>
    <option value="410">Mayantoc</option>
    <option value="411">Moncada</option>
    <option value="412">Paniqui</option>
    <option value="413">Pura</option>
    <option value="414">Ramos</option>
    <option value="415">San Clemente</option>
    <option value="416">San Jose</option>
    <option value="417">San Manuel</option>
    <option value="418">Santa Ignacia</option>
    <option value="419">Tarlac City</option>
    <option value="420">Victoria</option>
</select>
<select id="city-id-select-23" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="422">Botolan</option>
    <option value="423">Cabangan</option>
    <option value="424">Candelaria</option>
    <option value="425">Castillejos</option>
    <option value="426">Iba</option>
    <option value="427">Masinloc</option>
    <option value="428">Olongapo City</option>
    <option value="429">Palauig</option>
    <option value="430">San Antonio</option>
    <option value="431">San Felipe</option>
    <option value="432">San Marcelino</option>
    <option value="433">San Narciso</option>
    <option value="434">Santa Cruz</option>
    <option value="435">Subic</option>
</select>
<select id="city-id-select-24" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="437">Alfonso</option>
    <option value="438">Amadeo</option>
    <option value="439">Carmona</option>
    <option value="440">General Emilio Aguinaldo</option>
    <option value="441">General Mariano Alvarez</option>
    <option value="442">General Trias</option>
    <option value="443">Indang</option>
    <option value="444">Kawit</option>
    <option value="445">Magallanes</option>
    <option value="446">Maragondon</option>
    <option value="447">Mendez</option>
    <option value="448">Naic</option>
    <option value="449">Noveleta</option>
    <option value="450">Rosario</option>
    <option value="451">Silang</option>
    <option value="452">Tanza</option>
    <option value="453">Ternate</option>
    <option value="1621">Bacoor</option>
    <option value="1622">Cavite City</option>
    <option value="1623">Dasmarinas</option>
    <option value="1624">Imus</option>
    <option value="1625">Tagaytay City</option>
    <option value="1626">Trece Martires City</option>
</select>
<select id="city-id-select-25" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="455">Alaminos</option>
    <option value="456">Bay</option>
    <option value="457">Calauan</option>
    <option value="458">Cavinti</option>
    <option value="459">Famy</option>
    <option value="460">Kalayaan</option>
    <option value="461">Liliw</option>
    <option value="462">Luisiana</option>
    <option value="463">Lumban</option>
    <option value="464">Mabitac</option>
    <option value="465">Magdalena</option>
    <option value="466">Majayjay</option>
    <option value="467">Nagcarlan</option>
    <option value="468">Paete</option>
    <option value="469">Pagsanjan</option>
    <option value="470">Pakil</option>
    <option value="471">Pangil</option>
    <option value="472">Pila</option>
    <option value="473">Rizal</option>
    <option value="474">Santa Cruz</option>
    <option value="475">Santa Maria</option>
    <option value="476">Siniloan</option>
    <option value="477">Victoria</option>
    <option value="1627">Binan</option>
    <option value="1628">Cabuyao</option>
    <option value="1629">Calamba City</option>
    <option value="1630">Los Banos</option>
    <option value="1631">San Pablo City</option>
    <option value="1632">San Pedro</option>
    <option value="1633">Santa Rosa City</option>
</select>
<select id="city-id-select-26" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="479">Agoncillo</option>
    <option value="480">Alitagtag</option>
    <option value="481">Balayan</option>
    <option value="482">Balete</option>
    <option value="483">Bauan</option>
    <option value="484">Calaca</option>
    <option value="485">Calatagan</option>
    <option value="486">Cuenca</option>
    <option value="487">Ibaan</option>
    <option value="488">Laurel</option>
    <option value="489">Lemery</option>
    <option value="490">Lian</option>
    <option value="491">Lobo</option>
    <option value="492">Mabini</option>
    <option value="493">Malvar</option>
    <option value="494">Mataasnakahoy</option>
    <option value="495">Nasugbu</option>
    <option value="496">Padre Garcia</option>
    <option value="497">Rosario</option>
    <option value="498">San Jose</option>
    <option value="499">San Juan</option>
    <option value="500">San Luis</option>
    <option value="501">San Nicolas</option>
    <option value="502">San Pascual</option>
    <option value="503">Santa Teresita</option>
    <option value="504">Santo Tomas</option>
    <option value="505">Taal</option>
    <option value="506">Talisay</option>
    <option value="507">Taysan</option>
    <option value="508">Tingloy</option>
    <option value="509">Tuy</option>
    <option value="1634">Batangas City</option>
    <option value="1635">Lipa City</option>
    <option value="1636">Tanauan City</option>
</select>
<select id="city-id-select-27" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="511">Angono</option>
    <option value="512">Baras</option>
    <option value="513">Binangonan</option>
    <option value="514">Cainta</option>
    <option value="515">Cardona</option>
    <option value="516">Jalajala</option>
    <option value="517">Morong</option>
    <option value="518">Pililla</option>
    <option value="519">Rodriguez</option>
    <option value="520">San Mateo</option>
    <option value="521">Tanay</option>
    <option value="522">Taytay</option>
    <option value="523">Teresa</option>
    <option value="1637">Antipolo City</option>
</select>
<select id="city-id-select-28" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="525">Burdeos</option>
    <option value="526">General Nakar</option>
    <option value="527">Infanta</option>
    <option value="528">Jomalig</option>
    <option value="529">Lucban</option>
    <option value="530">Mauban</option>
    <option value="531">Pagbilao</option>
    <option value="532">Panukulan</option>
    <option value="533">Patnanungan</option>
    <option value="534">Polillo</option>
    <option value="535">Real</option>
    <option value="536">Sampaloc</option>
    <option value="537">Candelaria</option>
    <option value="538">Dolores</option>
    <option value="539">San Antonio</option>
    <option value="540">Sariaya</option>
    <option value="541">Tiaong</option>
    <option value="542">Agdangan</option>
    <option value="543">Buenavista</option>
    <option value="544">Catanauan</option>
    <option value="545">General Luna</option>
    <option value="546">Macalelon</option>
    <option value="547">Mulanay</option>
    <option value="548">Padre Burgos</option>
    <option value="549">Pitogo</option>
    <option value="550">San Andres</option>
    <option value="551">San Francisco</option>
    <option value="552">San Narciso</option>
    <option value="553">Unisan</option>
    <option value="554">Alabat</option>
    <option value="555">Atimonan</option>
    <option value="556">Calauag</option>
    <option value="557">Guinayangan</option>
    <option value="558">Gumaca</option>
    <option value="559">Lopez</option>
    <option value="560">Perez</option>
    <option value="561">Plaridel</option>
    <option value="562">Quezon</option>
    <option value="563">Tagkawayan</option>
    <option value="1638">Lucena City</option>
    <option value="1639">Tayabas City</option>
</select>
<select id="city-id-select-29" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="565">Boac</option>
    <option value="566">Buenavista</option>
    <option value="567">Gasan</option>
    <option value="568">Mogpog</option>
    <option value="569">Santa Cruz</option>
    <option value="570">Torrijos</option>
</select>
<select id="city-id-select-30" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="572">Abra de Ilog</option>
    <option value="573">Calintaan</option>
    <option value="574">Looc</option>
    <option value="575">Lubang</option>
    <option value="576">Magsaysay</option>
    <option value="577">Mamburao</option>
    <option value="578">Paluan</option>
    <option value="579">Rizal</option>
    <option value="580">Sablayan</option>
    <option value="581">San Jose</option>
    <option value="582">Santa Cruz</option>
</select>
<select id="city-id-select-31" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="584">Baco</option>
    <option value="585">Bansud</option>
    <option value="586">Bongabong</option>
    <option value="587">Bulalacao</option>
    <option value="588">Gloria</option>
    <option value="589">Mansalay</option>
    <option value="590">Naujan</option>
    <option value="591">Pinamalayan</option>
    <option value="592">Pola</option>
    <option value="593">Puerto Galera</option>
    <option value="594">Roxas</option>
    <option value="595">San Teodoro</option>
    <option value="596">Socorro</option>
    <option value="597">Victoria</option>
    <option value="1640">Calapan City</option>
</select>
<select id="city-id-select-32" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="599">Aborlan</option>
    <option value="600">Agutaya</option>
    <option value="601">Araceli</option>
    <option value="602">Balabac</option>
    <option value="603">Bataraza</option>
    <option value="604">Brooke's Point</option>
    <option value="605">Busuanga</option>
    <option value="606">Cagayancillo</option>
    <option value="607">Coron</option>
    <option value="608">Culion</option>
    <option value="609">Cuyo</option>
    <option value="610">Dumaran</option>
    <option value="611">El Nido</option>
    <option value="612">Kalayaan</option>
    <option value="613">Linapacan</option>
    <option value="614">Magsaysay</option>
    <option value="615">Narra</option>
    <option value="616">Puerto Princesa</option>
    <option value="617">Quezon</option>
    <option value="618">Rizal</option>
    <option value="619">Roxas</option>
    <option value="620">San Vicente</option>
    <option value="621">Sofronio Española</option>
    <option value="622">Taytay</option>
</select>
<select id="city-id-select-33" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="624">Alcantara</option>
    <option value="625">Banton</option>
    <option value="626">Cajidiocan</option>
    <option value="627">Calatrava</option>
    <option value="628">Concepcion</option>
    <option value="629">Corcuera</option>
    <option value="630">Ferrol</option>
    <option value="631">Looc</option>
    <option value="632">Magdiwang</option>
    <option value="633">Odiongan</option>
    <option value="634">Romblon</option>
    <option value="635">San Agustin</option>
    <option value="636">San Andres</option>
    <option value="637">San Fernando</option>
    <option value="638">San Jose</option>
    <option value="639">Santa Fe</option>
    <option value="640">Santa Maria</option>
</select>
<select id="city-id-select-34" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="642">Bacacay</option>
    <option value="643">Camalig</option>
    <option value="644">Daraga</option>
    <option value="645">Guinobatan</option>
    <option value="646">Jovellar</option>
    <option value="647">Libon</option>
    <option value="648">Malilipot</option>
    <option value="649">Malinao</option>
    <option value="650">Manito</option>
    <option value="651">Oas</option>
    <option value="652">Pio Duran</option>
    <option value="653">Polangui</option>
    <option value="654">Rapu-Rapu</option>
    <option value="655">Santo Domingo</option>
    <option value="656">Tabaco City</option>
    <option value="657">Tiwi</option>
    <option value="1641">Legazpi City</option>
    <option value="1642">Ligao City</option>
</select>
<select id="city-id-select-35" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="659">Basud</option>
    <option value="660">Capalonga</option>
    <option value="661">Daet</option>
    <option value="662">Jose Panganiban</option>
    <option value="663">Labo</option>
    <option value="664">Mercedes</option>
    <option value="665">Paracale</option>
    <option value="666">San Lorenzo Ruiz</option>
    <option value="667">San Vicente</option>
    <option value="668">Santa Elena</option>
    <option value="669">Talisay</option>
    <option value="670">Vinzons</option>
</select>
<select id="city-id-select-36" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="672">Baao</option>
    <option value="673">Balatan</option>
    <option value="674">Bato</option>
    <option value="675">Bombon</option>
    <option value="676">Buhi</option>
    <option value="677">Bula</option>
    <option value="678">Cabusao</option>
    <option value="679">Calabanga</option>
    <option value="680">Camaligan</option>
    <option value="681">Canaman</option>
    <option value="682">Caramoan</option>
    <option value="683">Del Gallego</option>
    <option value="684">Gainza</option>
    <option value="685">Garchitorena</option>
    <option value="686">Goa</option>
    <option value="687">Lagonoy</option>
    <option value="688">Libmanan</option>
    <option value="689">Lupi</option>
    <option value="690">Magarao</option>
    <option value="691">Milaor</option>
    <option value="692">Minalabac</option>
    <option value="693">Nabua</option>
    <option value="694">Ocampo</option>
    <option value="695">Pamplona</option>
    <option value="696">Pasacao</option>
    <option value="697">Pili</option>
    <option value="698">Presentacion</option>
    <option value="699">Ragay</option>
    <option value="700">Sagñay</option>
    <option value="701">San Fernando</option>
    <option value="702">San Jose</option>
    <option value="703">Sipocot</option>
    <option value="704">Siruma</option>
    <option value="705">Tigaon</option>
    <option value="706">Tinambac</option>
    <option value="1643">Iriga City</option>
    <option value="1644">Naga City</option>
</select>
<select id="city-id-select-37" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="708">Bagamanoc</option>
    <option value="709">Baras</option>
    <option value="710">Bato</option>
    <option value="711">Caramoran</option>
    <option value="712">Gigmoto</option>
    <option value="713">Pandan</option>
    <option value="714">Panganiban</option>
    <option value="715">San Andres</option>
    <option value="716">San Miguel</option>
    <option value="717">Viga</option>
    <option value="718">Virac</option>
</select>
<select id="city-id-select-38" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="720">Aroroy</option>
    <option value="721">Baleno</option>
    <option value="722">Balud</option>
    <option value="723">Batuan</option>
    <option value="724">Cataingan</option>
    <option value="725">Cawayan</option>
    <option value="726">Claveria</option>
    <option value="727">Dimasalang</option>
    <option value="728">Esperanza</option>
    <option value="729">Mandaon</option>
    <option value="730">Milagros</option>
    <option value="731">Mobo</option>
    <option value="732">Monreal</option>
    <option value="733">Palanas</option>
    <option value="734">Pio V. Corpuz</option>
    <option value="735">Placer</option>
    <option value="736">San Fernando</option>
    <option value="737">San Jacinto</option>
    <option value="738">San Pascual</option>
    <option value="739">Uson</option>
    <option value="1645">Masbate City</option>
</select>
<select id="city-id-select-39" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="741">Barcelona</option>
    <option value="742">Bulan</option>
    <option value="743">Bulusan</option>
    <option value="744">Casiguran</option>
    <option value="745">Castilla</option>
    <option value="746">Donsol</option>
    <option value="747">Gubat</option>
    <option value="748">Irosin</option>
    <option value="749">Juban</option>
    <option value="750">Magallanes</option>
    <option value="751">Matnog</option>
    <option value="752">Pilar</option>
    <option value="753">Prieto Diaz</option>
    <option value="754">Santa Magdalena</option>
    <option value="1646">Sorsogon City</option>
</select>
<select id="city-id-select-40" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="756">Altavas</option>
    <option value="757">Balete</option>
    <option value="758">Banga</option>
    <option value="759">Batan</option>
    <option value="760">Buruanga</option>
    <option value="761">Ibajay</option>
    <option value="762">Kalibo</option>
    <option value="763">Lezo</option>
    <option value="764">Libacao</option>
    <option value="765">Madalag</option>
    <option value="766">Makato</option>
    <option value="767">Malay</option>
    <option value="768">Malinao</option>
    <option value="769">Nabas</option>
    <option value="770">New Washington</option>
    <option value="771">Numancia</option>
    <option value="772">Tangalan</option>
</select>
<select id="city-id-select-41" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="774">Anini-y</option>
    <option value="775">Barbaza</option>
    <option value="776">Belison</option>
    <option value="777">Bugasong</option>
    <option value="778">Caluya</option>
    <option value="779">Culasi</option>
    <option value="780">Hamtic</option>
    <option value="781">Laua-An</option>
    <option value="782">Libertad</option>
    <option value="783">Pandan</option>
    <option value="784">Patnongon</option>
    <option value="785">San Jose de Buenavista</option>
    <option value="786">San Remigio</option>
    <option value="787">Sebaste</option>
    <option value="788">Sibalom</option>
    <option value="789">Tibiao</option>
    <option value="790">Tobias Fornier</option>
    <option value="791">Valderrama</option>
</select>
<select id="city-id-select-42" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="793">Cuartero</option>
    <option value="794">Dao</option>
    <option value="795">Dumalag</option>
    <option value="796">Dumarao</option>
    <option value="797">Ivisan</option>
    <option value="798">Jamindan</option>
    <option value="799">Maayon</option>
    <option value="800">Mambusao</option>
    <option value="801">Panay</option>
    <option value="802">Panitan</option>
    <option value="803">Pilar</option>
    <option value="804">Pontevedra</option>
    <option value="805">President Roxas</option>
    <option value="806">Sapian</option>
    <option value="807">Sigma</option>
    <option value="808">Tapaz</option>
    <option value="1647">Roxas City</option>
</select>
<select id="city-id-select-43" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="810">Buenavista</option>
    <option value="811">Jordan</option>
    <option value="812">Nueva Valencia</option>
    <option value="813">San Lorenzo</option>
    <option value="814">Sibunag</option>
</select>
<select id="city-id-select-44" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="816">Ajuy</option>
    <option value="817">Alimodian</option>
    <option value="818">Anilao</option>
    <option value="819">Badiangan</option>
    <option value="820">Balasan</option>
    <option value="821">Banate</option>
    <option value="822">Barotac Nuevo</option>
    <option value="823">Barotac Viejo</option>
    <option value="824">Batad</option>
    <option value="825">Bingawan</option>
    <option value="826">Cabatuan</option>
    <option value="827">Calinog</option>
    <option value="828">Carles</option>
    <option value="829">Concepcion</option>
    <option value="830">Dingle</option>
    <option value="831">Dueñas</option>
    <option value="832">Dumangas</option>
    <option value="833">Estancia</option>
    <option value="834">Guimbal</option>
    <option value="835">Igbaras</option>
    <option value="836">Janiuay</option>
    <option value="837">Lambunao</option>
    <option value="838">Leganes</option>
    <option value="839">Lemery</option>
    <option value="840">Leon</option>
    <option value="841">Maasin</option>
    <option value="842">Miagao</option>
    <option value="843">Mina</option>
    <option value="844">New Lucena</option>
    <option value="845">Oton</option>
    <option value="846">Passi City</option>
    <option value="847">Pavia</option>
    <option value="848">Pototan</option>
    <option value="849">San Dionisio</option>
    <option value="850">San Enrique</option>
    <option value="851">San Joaquin</option>
    <option value="852">San Miguel</option>
    <option value="853">San Rafael</option>
    <option value="854">Santa Barbara</option>
    <option value="855">Sara</option>
    <option value="856">Tigbauan</option>
    <option value="857">Tubungan</option>
    <option value="858">Zarraga</option>
    <option value="1648">Iloilo City</option>
</select>
<select id="city-id-select-45" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="860">Binalbagan</option>
    <option value="861">Calatrava</option>
    <option value="862">Candoni</option>
    <option value="863">Cauayan</option>
    <option value="864">Enrique B. Magalona</option>
    <option value="865">Hinigaran</option>
    <option value="866">Hinoba-an</option>
    <option value="867">Ilog</option>
    <option value="868">Isabela</option>
    <option value="869">La Castellana</option>
    <option value="870">Manapla</option>
    <option value="871">Moises Padilla</option>
    <option value="872">Murcia</option>
    <option value="873">Pontevedra</option>
    <option value="874">Pulupandan</option>
    <option value="875">Salvador Benedicto</option>
    <option value="876">San Enrique</option>
    <option value="877">Toboso</option>
    <option value="878">Valladolid</option>
    <option value="1649">Bacolod City</option>
    <option value="1650">Bago City</option>
    <option value="1651">Cadiz City</option>
    <option value="1652">Escalante City</option>
    <option value="1653">Himamaylan City</option>
    <option value="1654">Kabankalan City</option>
    <option value="1655">La Carlota City</option>
    <option value="1656">Sagay City</option>
    <option value="1657">San Carlos City</option>
    <option value="1658">Silay City</option>
    <option value="1659">Talisay City</option>
    <option value="1660">Victorias City</option>
    <option value="1792">Sipalay City</option>
</select>
<select id="city-id-select-46" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="880">Alburquerque</option>
    <option value="882">Baclayon</option>
    <option value="883">Balilihan</option>
    <option value="884">Calape</option>
    <option value="885">Catigbian</option>
    <option value="886">Corella</option>
    <option value="887">Cortes</option>
    <option value="888">Dauis</option>
    <option value="889">Loon</option>
    <option value="890">Maribojoc</option>
    <option value="891">Panglao</option>
    <option value="892">Sikatuna</option>
    <option value="893">Tubigon,</option>
    <option value="894">Bien Unido</option>
    <option value="895">Buenavista</option>
    <option value="896">Clarin</option>
    <option value="897">Dagohoy</option>
    <option value="898">Danao</option>
    <option value="899">Getafe</option>
    <option value="900">Inabanga</option>
    <option value="901">President Carlos P. Garcia</option>
    <option value="902">San Isidro</option>
    <option value="903">Sagbayan</option>
    <option value="905">Talibon</option>
    <option value="906">Trinidad</option>
    <option value="907">Ubay</option>
    <option value="908">Alicia</option>
    <option value="909">Anda</option>
    <option value="910">Batuan</option>
    <option value="911">Bilar</option>
    <option value="912">Candijay</option>
    <option value="913">Carmen</option>
    <option value="914">Dimiao</option>
    <option value="915">Duero</option>
    <option value="916">Garcia Hernandez</option>
    <option value="917">Guindulman</option>
    <option value="918">Jagna</option>
    <option value="919">Lila</option>
    <option value="920">Loay</option>
    <option value="921">Loboc</option>
    <option value="922">Mabini</option>
    <option value="923">Pilar</option>
    <option value="924">Sevilla</option>
    <option value="925">Sierra Bullones</option>
    <option value="926">Valencia</option>
    <option value="1661">Antequera</option>
    <option value="1662">Getafe (Jetafe)</option>
    <option value="1663">Pres. Carlos P. Garcia (Pitogo)</option>
    <option value="1664">Sagbayan (Borja)</option>
    <option value="1665">San Miguel</option>
    <option value="1666">Tagbilaran City</option>
</select>
<select id="city-id-select-47" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="928">Alcantara</option>
    <option value="929">Alcoy</option>
    <option value="930">Alegria</option>
    <option value="931">Aloguinsan</option>
    <option value="932">Argao</option>
    <option value="933">Asturias</option>
    <option value="934">Badian</option>
    <option value="935">Balamban</option>
    <option value="936">Bantayan</option>
    <option value="937">Barili</option>
    <option value="938">Boljoon</option>
    <option value="939">Borbo</option>
    <option value="940">Carmen</option>
    <option value="941">Catmon</option>
    <option value="942">Compostela</option>
    <option value="943">Consolacion</option>
    <option value="944">Cordova</option>
    <option value="945">Daanbantayan</option>
    <option value="946">Dalaguete</option>
    <option value="947">Dumanjug</option>
    <option value="948">Ginatilan</option>
    <option value="949">Liloan</option>
    <option value="950">Madridejos</option>
    <option value="951">Malabuyoc</option>
    <option value="952">Medellin</option>
    <option value="953">Minglanilla</option>
    <option value="954">Moalboal</option>
    <option value="955">Oslob</option>
    <option value="956">Pilar</option>
    <option value="957">Pinamungajan</option>
    <option value="958">Poro</option>
    <option value="959">Ronda</option>
    <option value="960">Samboan</option>
    <option value="961">San Fernando</option>
    <option value="962">San Francisco</option>
    <option value="963">San Remigio</option>
    <option value="964">Santa Fe</option>
    <option value="965">Santander</option>
    <option value="966">Sibonga</option>
    <option value="967">Sogod</option>
    <option value="968">Tabogon</option>
    <option value="969">Tabuelan</option>
    <option value="970">Tuburan</option>
    <option value="971">Tudela</option>
    <option value="1686">Danao City</option>
    <option value="1689">Lapu-Lapu City</option>
    <option value="1693">Mandaue City</option>
    <option value="1712">Talisay City</option>
    <option value="1782">Toledo City</option>
    <option value="1783">Bogo</option>
    <option value="1784">Naga</option>
    <option value="1785">Cebu City</option>
    <option value="1790">Carcar</option>
</select>
<select id="city-id-select-48" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="973">Amlan</option>
    <option value="974">Ayungon</option>
    <option value="975">Bacong</option>
    <option value="976">Basay</option>
    <option value="977">Bindoy</option>
    <option value="978">Dauin</option>
    <option value="979">Jimalalud</option>
    <option value="980">La Libertad</option>
    <option value="981">Mabinay</option>
    <option value="982">Manjuyod</option>
    <option value="983">Pamplona</option>
    <option value="984">San Jose</option>
    <option value="985">Santa Catalina</option>
    <option value="986">Siaton</option>
    <option value="987">Sibulan</option>
    <option value="988">Tayasan</option>
    <option value="989">Valencia</option>
    <option value="990">Vallehermoso</option>
    <option value="991">Zamboanguita</option>
    <option value="1715">Bais City</option>
    <option value="1716">Bayawan City (Tulong)</option>
    <option value="1717">Bindoy (Payabon)</option>
    <option value="1718">Canlaon City</option>
    <option value="1719">Dumaguete City</option>
    <option value="1720">Guihulngan</option>
    <option value="1721">Tanjay City</option>
</select>
<select id="city-id-select-50" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="993">Almeria</option>
    <option value="994">Biliran</option>
    <option value="995">Cabucgayan</option>
    <option value="996">Caibiran</option>
    <option value="997">Culaba</option>
    <option value="998">Kawayan</option>
    <option value="999">Maripipi</option>
    <option value="1000">Naval</option>
</select>
<select id="city-id-select-51" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1002">Arteche</option>
    <option value="1003">Balangiga</option>
    <option value="1004">Balangkayan</option>
    <option value="1005">Can-Avid</option>
    <option value="1006">Dolores</option>
    <option value="1007">General MacArthur</option>
    <option value="1008">Giporlos</option>
    <option value="1009">Guiuan</option>
    <option value="1010">Hernani</option>
    <option value="1011">Jipapad</option>
    <option value="1012">Lawaan</option>
    <option value="1013">Llorente</option>
    <option value="1014">Maslog</option>
    <option value="1015">Maydolong</option>
    <option value="1016">Mercedes</option>
    <option value="1017">Oras</option>
    <option value="1018">Quinapondan</option>
    <option value="1019">Salcedo</option>
    <option value="1020">San Julian</option>
    <option value="1021">San Policarpo</option>
    <option value="1022">Sulat</option>
    <option value="1023">Taft</option>
    <option value="1728">Borongan City</option>
</select>
<select id="city-id-select-52" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1025">Abuyog</option>
    <option value="1026">Alangalang</option>
    <option value="1027">Albuera</option>
    <option value="1028">Babatngon</option>
    <option value="1029">Barugo</option>
    <option value="1030">Bato</option>
    <option value="1031">Burauen</option>
    <option value="1032">Calubian</option>
    <option value="1033">Capoocan</option>
    <option value="1034">Carigara</option>
    <option value="1035">Dagami</option>
    <option value="1036">Dulag</option>
    <option value="1037">Hilongos</option>
    <option value="1038">Hindang</option>
    <option value="1039">Inopacan</option>
    <option value="1040">Isabel</option>
    <option value="1041">Jaro</option>
    <option value="1043">Julita</option>
    <option value="1044">Kananga</option>
    <option value="1045">La Paz</option>
    <option value="1046">Leyte</option>
    <option value="1047">MacArthur</option>
    <option value="1048">Mahaplag</option>
    <option value="1049">Matag-Ob</option>
    <option value="1050">Matalom</option>
    <option value="1051">Mayorga</option>
    <option value="1052">Merida</option>
    <option value="1053">Palo</option>
    <option value="1054">Palompon</option>
    <option value="1055">Pastrana</option>
    <option value="1056">San Isidro</option>
    <option value="1057">San Miguel</option>
    <option value="1058">Santa Fe</option>
    <option value="1059">Tabango</option>
    <option value="1060">Tabontabon</option>
    <option value="1061">Tanauan</option>
    <option value="1062">Tolosa</option>
    <option value="1063">Tunga</option>
    <option value="1064">Villab</option>
    <option value="1729">Baybay</option>
    <option value="1730">Javier (Bugho)</option>
    <option value="1731">Ormoc City</option>
    <option value="1732">Tacloban City</option>
</select>
<select id="city-id-select-53" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1066">Allen</option>
    <option value="1067">Biri</option>
    <option value="1068">Bobon</option>
    <option value="1069">Capul</option>
    <option value="1070">Catarman</option>
    <option value="1071">Catubig</option>
    <option value="1072">Gamay</option>
    <option value="1073">Laoang</option>
    <option value="1074">Lapinig</option>
    <option value="1075">Las Navas</option>
    <option value="1076">Lavezares</option>
    <option value="1077">Lope De Vega</option>
    <option value="1078">Mapanas</option>
    <option value="1079">Mondragon</option>
    <option value="1080">Palapag</option>
    <option value="1081">Pambujan</option>
    <option value="1082">Rosario</option>
    <option value="1083">San Antonio</option>
    <option value="1084">San Isidro</option>
    <option value="1085">San Jose</option>
    <option value="1086">San Roque</option>
    <option value="1087">San Vicente</option>
    <option value="1088">Silvino Lobos</option>
    <option value="1089">Victoria</option>
</select>
<select id="city-id-select-54" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1091">Almagro</option>
    <option value="1092">Basey</option>
    <option value="1093">Calbiga</option>
    <option value="1094">Daram</option>
    <option value="1095">Gandara</option>
    <option value="1096">Hinabangan</option>
    <option value="1097">Jiabong</option>
    <option value="1098">Marabut</option>
    <option value="1099">Matuguinao</option>
    <option value="1100">Motiong</option>
    <option value="1101">Pagsanghan</option>
    <option value="1102">Paranas</option>
    <option value="1103">Pinabacdao</option>
    <option value="1104">San Jorge</option>
    <option value="1105">San Jose De Buan</option>
    <option value="1106">San Sebastian</option>
    <option value="1107">Santa Margarita</option>
    <option value="1108">Santa Rita</option>
    <option value="1109">Santo Niño</option>
    <option value="1110">Tagapul-An</option>
    <option value="1111">Talalora</option>
    <option value="1112">Tarangnan</option>
    <option value="1113">Villareal</option>
    <option value="1114">Zumarraga</option>
    <option value="1733">Calbayog City</option>
    <option value="1734">Catbalogan City</option>
    <option value="1735">Paranas (Wright)</option>
    <option value="1736">Santo Nino</option>
    <option value="1737">Tarangan</option>
</select>
<select id="city-id-select-55" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1116">Anahawan</option>
    <option value="1117">Bontoc</option>
    <option value="1118">Hinunangan</option>
    <option value="1119">Libagon</option>
    <option value="1120">Liloan</option>
    <option value="1121">Limasawa</option>
    <option value="1122">Maasin City</option>
    <option value="1123">Macrohon</option>
    <option value="1124">Malitbog</option>
    <option value="1125">Padre Burgos</option>
    <option value="1126">Pintuyan</option>
    <option value="1127">Saint Bernard</option>
    <option value="1128">San Francisco</option>
    <option value="1130">San Ricardo</option>
    <option value="1131">Silago</option>
    <option value="1132">Sogod</option>
    <option value="1133">Tomas Oppus</option>
    <option value="1738">Hinundayan</option>
    <option value="1739">San Juan (Cabalian)</option>
</select>
<select id="city-id-select-56" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1135">Baliguian</option>
    <option value="1136">Godod</option>
    <option value="1137">Gutalac</option>
    <option value="1139">Kalawit</option>
    <option value="1140">Katipunan</option>
    <option value="1141">La Libertad</option>
    <option value="1142">Labason</option>
    <option value="1143">Leon B. Postigo(Bacungan)</option>
    <option value="1144">Liloy</option>
    <option value="1145">Manukan</option>
    <option value="1146">Mutia</option>
    <option value="1147">Piñan</option>
    <option value="1148">Polanco</option>
    <option value="1149">Pres. Manuel A. Roxas</option>
    <option value="1150">Rizal</option>
    <option value="1151">Salug</option>
    <option value="1152">Sergio Osmeña Sr.</option>
    <option value="1153">Siayan</option>
    <option value="1154">Sibuco</option>
    <option value="1155">Sibutad</option>
    <option value="1156">Sindangan</option>
    <option value="1157">Siocon</option>
    <option value="1158">Sirawai</option>
    <option value="1159">Tampilisan</option>
    <option value="1741">Dapitan City</option>
    <option value="1742">Dipolog City</option>
    <option value="1743">Jose Dalman (Ponot)</option>
    <option value="1744">Pinan (New Pinan)</option>
</select>
<select id="city-id-select-57" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1161">Aurora</option>
    <option value="1162">Bayog</option>
    <option value="1163">Dimataling</option>
    <option value="1164">Dinas</option>
    <option value="1165">Dumalinao</option>
    <option value="1166">Dumingag</option>
    <option value="1167">Guipos</option>
    <option value="1168">Josefina</option>
    <option value="1169">Kumalarang</option>
    <option value="1170">Labangan</option>
    <option value="1171">Lakewood</option>
    <option value="1172">Lapuyan</option>
    <option value="1173">Mahayag</option>
    <option value="1174">Margosatubig</option>
    <option value="1175">Midsalip</option>
    <option value="1176">Molave</option>
    <option value="1177">Pitogo</option>
    <option value="1179">San Miguel</option>
    <option value="1180">San Pablo</option>
    <option value="1182">Tabina</option>
    <option value="1183">Tambulig</option>
    <option value="1184">Tigbao</option>
    <option value="1185">Tukuran</option>
    <option value="1186">Vincenzo A. Sagun</option>
    <option value="1746">Pagadian City</option>
    <option value="1747">Ramon Magsaysay (Liargo)</option>
    <option value="1748">Sominot (Don Mariano Marcos)</option>
</select>
<select id="city-id-select-58" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1188">Alicia</option>
    <option value="1189">Buug</option>
    <option value="1190">Diplahan</option>
    <option value="1191">Imelda</option>
    <option value="1192">Ipil</option>
    <option value="1193">Kabasalan</option>
    <option value="1194">Mabuhay</option>
    <option value="1195">Malangas</option>
    <option value="1196">Naga</option>
    <option value="1197">Olutanga</option>
    <option value="1198">Payao</option>
    <option value="1199">Roseller T. Lim</option>
    <option value="1200">Siay</option>
    <option value="1201">Talusan</option>
    <option value="1202">Titay</option>
    <option value="1203">Tungawan</option>
</select>
<select id="city-id-select-59" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1205">Baungon</option>
    <option value="1206">Cabanglasan</option>
    <option value="1207">Damulog</option>
    <option value="1208">Dangcagan</option>
    <option value="1209">Don Carlos</option>
    <option value="1210">Impasugong</option>
    <option value="1211">Kadingilan</option>
    <option value="1212">Kalilangan</option>
    <option value="1213">Kibawe</option>
    <option value="1214">Kitaotao</option>
    <option value="1215">Lantapan</option>
    <option value="1216">Libona</option>
    <option value="1217">Malitbog</option>
    <option value="1218">Manolo Fortich</option>
    <option value="1219">Maramag</option>
    <option value="1220">Pangantucan</option>
    <option value="1221">Quezon</option>
    <option value="1222">San Fernando</option>
    <option value="1223">Sumilao</option>
    <option value="1224">Talakag</option>
    <option value="1751">Malaybalay City</option>
    <option value="1752">Valencia City</option>
</select>
<select id="city-id-select-60" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1226">Catarman</option>
    <option value="1227">Guinsiliban</option>
    <option value="1228">Mahinog</option>
    <option value="1229">Mambajao</option>
    <option value="1230">Sagay</option>
</select>
<select id="city-id-select-61" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1232">Bacolod</option>
    <option value="1233">Baloi</option>
    <option value="1234">Baroy</option>
    <option value="1235">Kapatagan</option>
    <option value="1236">Kauswagan</option>
    <option value="1237">Kolambugan</option>
    <option value="1238">Lala</option>
    <option value="1239">Linamon</option>
    <option value="1240">Magsaysay</option>
    <option value="1241">Maigo</option>
    <option value="1242">Matungao</option>
    <option value="1243">Munai</option>
    <option value="1244">Nunungan</option>
    <option value="1245">Pantao Ragat</option>
    <option value="1246">Pantar</option>
    <option value="1247">Poona Piagapo</option>
    <option value="1248">Salvador</option>
    <option value="1249">Sapad</option>
    <option value="1250">Sultan Naga Dimaporo(Karomatan)</option>
    <option value="1251">Tagoloan</option>
    <option value="1252">Tangcal</option>
    <option value="1253">Tubod City</option>
    <option value="1753">Iligan City</option>
</select>
<select id="city-id-select-62" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1255">Aloran</option>
    <option value="1256">Baliangao</option>
    <option value="1257">Bonifacio</option>
    <option value="1258">Calamba</option>
    <option value="1259">Clarin</option>
    <option value="1260">Concepcion</option>
    <option value="1262">Jimenez</option>
    <option value="1263">Lopez Jaena</option>
    <option value="1264">Panaon</option>
    <option value="1265">Plaridel</option>
    <option value="1266">Sapang Dalaga</option>
    <option value="1267">Sinacaban</option>
    <option value="1268">Tudela</option>
    <option value="1755">Don Victoriano Chiongbian</option>
    <option value="1756">Oroquieta City</option>
    <option value="1757">Ozamis City</option>
    <option value="1758">Tangub City</option>
</select>
<select id="city-id-select-63" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1270">Alubijid</option>
    <option value="1271">Balingasag</option>
    <option value="1272">Balingoan</option>
    <option value="1273">Binuangan</option>
    <option value="1274">Claveria</option>
    <option value="1275">Gitagum</option>
    <option value="1276">Initao</option>
    <option value="1277">Jasaan</option>
    <option value="1278">Kinoguitan</option>
    <option value="1279">Lagonglong</option>
    <option value="1280">Laguindingan</option>
    <option value="1281">Libertad</option>
    <option value="1282">Lugait</option>
    <option value="1283">Magsaysay (Linugos)</option>
    <option value="1284">Manticao</option>
    <option value="1285">Medina</option>
    <option value="1286">Naawan</option>
    <option value="1287">Opol</option>
    <option value="1288">Salay</option>
    <option value="1289">Sugbongcogon</option>
    <option value="1290">Tagoloan</option>
    <option value="1291">Talisayan</option>
    <option value="1292">Villanueva</option>
    <option value="1759">Cagayan De Oro City</option>
    <option value="1760">El Salvador City</option>
    <option value="1761">Gingoog City</option>
</select>
<select id="city-id-select-64" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1294">Compostela</option>
    <option value="1296">Mabini (Dona Alicia)</option>
    <option value="1297">Maco</option>
    <option value="1298">Maragusan (San Mariano)</option>
    <option value="1299">Mawab</option>
    <option value="1300">Monkayo</option>
    <option value="1301">Montevista</option>
    <option value="1302">Nabunturan</option>
    <option value="1303">New Bataan</option>
    <option value="1304">Pantukan</option>
    <option value="1762">Laak (San Vicente)</option>
</select>
<select id="city-id-select-65" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1306">Asuncion (Saug)</option>
    <option value="1307">Braulio E. Dujali</option>
    <option value="1308">Carmen</option>
    <option value="1309">Kapalong</option>
    <option value="1310">New Corella</option>
    <option value="1311">San Isidro</option>
    <option value="1312">Santo Tomas</option>
    <option value="1313">Talaingod</option>
    <option value="1763">Panabo City</option>
    <option value="1764">Samal Island Garden City</option>
    <option value="1765">Tagum City</option>
</select>
<select id="city-id-select-66" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1315">Bansalan</option>
    <option value="1316">Hagonoy</option>
    <option value="1317">Kiblawan</option>
    <option value="1318">Magsaysay</option>
    <option value="1319">Malalag</option>
    <option value="1320">Matanao</option>
    <option value="1321">Padada</option>
    <option value="1322">Santa Cruz</option>
    <option value="1323">Sulop</option>
    <option value="1786">Davao City</option>
    <option value="1787">Digos City</option>
</select>
<select id="city-id-select-67" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1325">Don Marcelino</option>
    <option value="1326">Jose Abad Santos (Trinidad)</option>
    <option value="1327">Malita</option>
    <option value="1328">Santa Maria</option>
    <option value="1329">Sarangani</option>
</select>
<select id="city-id-select-68" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1332">Baganga</option>
    <option value="1333">Banaybanay</option>
    <option value="1334">Boston</option>
    <option value="1335">Caraga</option>
    <option value="1336">Cateel</option>
    <option value="1337">Governor Generoso</option>
    <option value="1338">Lupon</option>
    <option value="1339">Manay</option>
    <option value="1340">San Isidro</option>
    <option value="1341">Tarragona</option>
    <option value="1766">Mati City</option>
</select>
<select id="city-id-select-69" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1343">Alamada</option>
    <option value="1344">Aleosan</option>
    <option value="1345">Antipas</option>
    <option value="1346">Arakan</option>
    <option value="1347">Banisilan</option>
    <option value="1348">Carmen</option>
    <option value="1349">Kabacan</option>
    <option value="1350">Libungan</option>
    <option value="1351">Magpet</option>
    <option value="1352">Makilala</option>
    <option value="1353">Matalam</option>
    <option value="1354">Midsayap</option>
    <option value="1355">M'Lang</option>
    <option value="1356">Pigkawayan</option>
    <option value="1357">Pikit</option>
    <option value="1358">President Roxas</option>
    <option value="1359">Tulunan</option>
    <option value="1767">Kidapawan City</option>
</select>
<select id="city-id-select-70" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1361">Alabel</option>
    <option value="1362">Glan</option>
    <option value="1363">Kiamba</option>
    <option value="1364">Maasim</option>
    <option value="1365">Maitum</option>
    <option value="1366">Malapatan</option>
    <option value="1367">Malungon</option>
</select>
<select id="city-id-select-71" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1369">General Santos City (Dadiangas)</option>
    <option value="1370">Banga</option>
    <option value="1371">Koronadal City</option>
    <option value="1372">Lake Sebu</option>
    <option value="1373">Norala</option>
    <option value="1374">Polomolok</option>
    <option value="1375">Santo Nino</option>
    <option value="1376">Surallah</option>
    <option value="1377">Tampakan</option>
    <option value="1378">Tantangan</option>
    <option value="1379">T'Boli</option>
    <option value="1380">Tupi</option>
</select>
<select id="city-id-select-72" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1382">Bagumbayan</option>
    <option value="1383">Columbio</option>
    <option value="1384">Esperanza</option>
    <option value="1385">Isulan</option>
    <option value="1386">Kalamansig</option>
    <option value="1387">Lambayong (Mariano Marcos)</option>
    <option value="1388">Lebak</option>
    <option value="1389">Lutayan</option>
    <option value="1390">Palimbang</option>
    <option value="1391">President Quirino</option>
    <option value="1392">Sen. Ninoy Aquino</option>
    <option value="1768">Tacurong City</option>
</select>
<select id="city-id-select-73" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1394">Buenavista</option>
    <option value="1395">Carmen</option>
    <option value="1396">Jabonga</option>
    <option value="1397">Kitcharao</option>
    <option value="1398">Las Nieves</option>
    <option value="1399">Magallanes</option>
    <option value="1400">Nasipit</option>
    <option value="1401">Remedios T. Romualdez</option>
    <option value="1402">Santiago</option>
    <option value="1403">Tubay</option>
    <option value="1769">Butuan City</option>
    <option value="1770">Cabadbaran City</option>
</select>
<select id="city-id-select-74" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1406">Bunawan</option>
    <option value="1407">Esperanza</option>
    <option value="1408">La Paz</option>
    <option value="1409">Loreto</option>
    <option value="1410">Prosperidad</option>
    <option value="1411">Rosario</option>
    <option value="1412">San Francisco</option>
    <option value="1413">San Luis</option>
    <option value="1414">Santa Josefa</option>
    <option value="1415">Sibagat</option>
    <option value="1416">Talacogon</option>
    <option value="1417">Trento</option>
    <option value="1418">Veruela</option>
    <option value="1771">Bayugan City</option>
</select>
<select id="city-id-select-75" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1420">Basilisa (Rizal)</option>
    <option value="1421">Cagdianao</option>
    <option value="1422">Dinagat</option>
    <option value="1423">Libjo (Abjor)</option>
    <option value="1424">Loreto</option>
    <option value="1425">San Jose</option>
    <option value="1426">Tubajon</option>
</select>
<select id="city-id-select-76" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1428">Alegria</option>
    <option value="1429">Bacuag</option>
    <option value="1430">Burgos</option>
    <option value="1431">Claver</option>
    <option value="1432">Dapa</option>
    <option value="1433">Del Carmen</option>
    <option value="1434">General Luna</option>
    <option value="1435">Gigaquit</option>
    <option value="1436">Mainit</option>
    <option value="1437">Malimono</option>
    <option value="1438">Pilar</option>
    <option value="1439">Placer</option>
    <option value="1440">San Benito</option>
    <option value="1441">San Francisco (Anao-Aon)</option>
    <option value="1442">San Isidro</option>
    <option value="1443">Santa Monica (Sapao)</option>
    <option value="1444">Sison</option>
    <option value="1445">Socorro</option>
    <option value="1446">Tagana-an</option>
    <option value="1447">Tubod</option>
    <option value="1774">Surigao City (Capital)</option>
</select>
<select id="city-id-select-77" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1449">Barobo</option>
    <option value="1450">Bayabas</option>
    <option value="1451">Cagwait</option>
    <option value="1452">Cantilan</option>
    <option value="1453">Carmen</option>
    <option value="1454">Carrascal</option>
    <option value="1455">Cortes</option>
    <option value="1456">Hinatuan</option>
    <option value="1457">Lanuza</option>
    <option value="1458">Lianga</option>
    <option value="1459">Lingig</option>
    <option value="1460">Madrid</option>
    <option value="1461">Marihatag</option>
    <option value="1462">San Agustin</option>
    <option value="1463">San Miguel</option>
    <option value="1464">Tagbina</option>
    <option value="1465">Tago</option>
    <option value="1775">Bislig City</option>
    <option value="1776">Tandag City</option>
</select>
<select id="city-id-select-78" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1467">Akbar</option>
    <option value="1468">Al-Barka</option>
    <option value="1469">Hadji Mohammad Ajul</option>
    <option value="1470">Hadji Muhtamad</option>
    <option value="1471">Isabela City</option>
    <option value="1472">Lamitan City</option>
    <option value="1473">Lantawan</option>
    <option value="1474">Maluso</option>
    <option value="1475">Sumisip</option>
    <option value="1476">Tabuan-Lasa</option>
    <option value="1477">Tipo-Tipo</option>
    <option value="1478">Tuburan</option>
    <option value="1479">Ungkaya Pukan</option>
</select>
<select id="city-id-select-79" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1481">Bacolod-Kalawi (Bacolod-Grande)</option>
    <option value="1482">Balabagan</option>
    <option value="1483">Balindong (Watu)</option>
    <option value="1484">Bayang</option>
    <option value="1485">Binidayan</option>
    <option value="1486">Buadiposo-Buntong</option>
    <option value="1487">Bubong</option>
    <option value="1488">Bumbaran</option>
    <option value="1489">Butig</option>
    <option value="1490">Calanogas</option>
    <option value="1491">Ditsaan-Ramain</option>
    <option value="1492">Ganassi</option>
    <option value="1493">Kapai</option>
    <option value="1494">Kapatagan</option>
    <option value="1495">Lumba-Bayabao</option>
    <option value="1496">Lumbaca-Unayan</option>
    <option value="1497">Lumbatan</option>
    <option value="1498">Lumbayanague</option>
    <option value="1499">Madalum</option>
    <option value="1500">Madamba (Uya-an)</option>
    <option value="1501">Maguing</option>
    <option value="1502">Malabang</option>
    <option value="1503">Marantao (Inudaran)</option>
    <option value="1504">Marogong</option>
    <option value="1505">Masiu</option>
    <option value="1506">Mulondo</option>
    <option value="1507">Pagayawan</option>
    <option value="1508">Piagapo</option>
    <option value="1509">Picong (Sultan Gumander)</option>
    <option value="1510">Poona Bayabao (Gata)</option>
    <option value="1511">Pualas</option>
    <option value="1512">Saguiaran</option>
    <option value="1513">Sultan Dumalondong</option>
    <option value="1514">Tagoloan II</option>
    <option value="1515">Tamparan</option>
    <option value="1516">Taraka</option>
    <option value="1517">Tubaran</option>
    <option value="1518">Tugaya</option>
    <option value="1519">Wao</option>
    <option value="1777">Marawi City</option>
</select>
<select id="city-id-select-80" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1521">Ampatuan</option>
    <option value="1522">Barira</option>
    <option value="1523">Buldon</option>
    <option value="1524">Buluan</option>
    <option value="1525">Datu Abdullah Sangki</option>
    <option value="1526">Datu Anggal Midtimbang</option>
    <option value="1527">Datu Blah T. Sinsuat</option>
    <option value="1528">Datu Hoffer Ampatuan</option>
    <option value="1529">Datu Odin Sinsuat</option>
    <option value="1530">Datu Paglas</option>
    <option value="1531">Datu Piang</option>
    <option value="1532">Datu Salibo</option>
    <option value="1533">Datu Saudi-Ampatuan</option>
    <option value="1534">Datu Unsay</option>
    <option value="1535">Gen. S. K. Pendatun</option>
    <option value="1536">Guindulungan</option>
    <option value="1537">Kabuntalan</option>
    <option value="1538">Mamasapano</option>
    <option value="1539">Mangudadatu</option>
    <option value="1540">Matanog</option>
    <option value="1541">Northern Kabuntalan</option>
    <option value="1542">Pagagawan</option>
    <option value="1543">Pagalungan</option>
    <option value="1544">Paglat</option>
    <option value="1545">Pandag</option>
    <option value="1546">Parang</option>
    <option value="1547">Rajah Buayan</option>
    <option value="1548">Shariff Aguak (Maganoy)</option>
    <option value="1549">Shariff Saydona Mustapha</option>
    <option value="1550">South Upi</option>
    <option value="1551">Sultan Kudarat</option>
    <option value="1552">Sultan Mastura</option>
    <option value="1553">Sultan sa Barongis</option>
    <option value="1554">Sultan Sumagka (Talitay)</option>
    <option value="1555">Talayan</option>
    <option value="1556">Upi</option>
    <option value="1779">Talitay</option>
    <option value="1791">Cotabato</option>
</select>
<select id="city-id-select-81" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1558">Banguingui</option>
    <option value="1559">Hadji Panglima Tahil (Marungga)</option>
    <option value="1560">Indanan</option>
    <option value="1561">Jolo</option>
    <option value="1562">Caluang</option>
    <option value="1563">Lugus</option>
    <option value="1564">Luuk</option>
    <option value="1565">Maimbung</option>
    <option value="1566">Old Panamao</option>
    <option value="1567">Omar</option>
    <option value="1568">Pandami</option>
    <option value="1569">Panglima Estino (New Panamao)</option>
    <option value="1570">Pangutaran</option>
    <option value="1571">Parang</option>
    <option value="1572">Pata</option>
    <option value="1573">Patikul</option>
    <option value="1574">Siasi</option>
    <option value="1575">Talipao</option>
    <option value="1576">Tapul</option>
    <option value="1780">Kalingalan Caluang</option>
</select>
<select id="city-id-select-82" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1578">Bongao</option>
    <option value="1579">Languyan</option>
    <option value="1580">Mapun</option>
    <option value="1581">Panglima Sugala</option>
    <option value="1582">Sapa-Sapa</option>
    <option value="1583">Sibutu -</option>
    <option value="1584">Simunul</option>
    <option value="1585">Sitangkai</option>
    <option value="1586">South Ubian</option>
    <option value="1587">Tandubas</option>
    <option value="1588">Turtle Islands</option>
</select>
<select id="city-id-select-83" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1589">Zamboanga City</option>
</select>
<select id="city-id-select-49" class="light br3 required long x-normal city-select hidden">
    <option value="">Choose</option>
    <option value="1722">Enrique Villanueva</option>
    <option value="1723">Larena</option>
    <option value="1724">Lazi</option>
    <option value="1725">Maria</option>
    <option value="1726">San Juan</option>
    <option value="1727">Siquijor</option>
</select>
</div>