<select id="province">
    <option value="">Choose</option>
    <option value="Abra" ></option>
    <option value="Agusan del Norte"></option>
    <option value="Agusan del Sur"></option>
    <option value="Aklan" ></option>
    <option value="Albay" ></option>
    <option value="Antique" ></option>
    <option value="Apayao" ></option>
    <option value="Aurora" ></option>
    <option value="Basilan" ></option>
    <option value="Bataan" ></option>
    <option value="Batanes" ></option>
    <option value="Batangas" ></option>
    <option value="Benguet" ></option>
    <option value="Biliran" ></option>
    <option value="Bohol" ></option>
    <option value="Bukidnon" ></option>
    <option value="Bulacan" ></option>
    <option value="Cagayan" ></option>
    <option value="Camarines Norte" ></option>
    <option value="Camarines Sur" ></option>
    <option value="Camiguin" ></option>
    <option value="Capiz" ></option>
    <option value="Catanduanes" ></option>
    <option value="Cavite" ></option>
    <option value="Cebu" ></option>
    <option value="Compostela Valley" ></option>
    <option value="Cotabato" ></option>
    <option value="Davao del Norte" ></option>
    <option value="Davao del Sur" ></option>
    <option value="Davao Occidental" ></option>
    <option value="Davao Oriental" ></option>
    <option value="Dinagat Islands" ></option>
    <option value="Eastern Samar" ></option>
    <option value="Guimaras" ></option>
    <option value="Ifugao" ></option>
    <option value="Ilocos Norte" ></option>
    <option value="Ilocos Sur" ></option>
    <option value="Iloilo" ></option>
    <option value="Isabela" ></option>
    <option value="Kalinga" ></option>
    <option value="La Union" ></option>
    <option value="Laguna" ></option>
    <option value="Lanao del Norte" ></option>
    <option value="Lanao del Sur" ></option>
    <option value="Leyte" ></option>
    <option value="Maguindanao" ></option>
    <option value="Marinduque" ></option>
    <option value="Masbate" ></option>
    <option value="Metro Manila" ></option>
    <option value="Misamis Occidental" ></option>
    <option value="Misamis Oriental" ></option>
    <option value="Mountain Province" ></option>
    <option value="Negros Occidental" ></option>
    <option value="Negros Oriental" ></option>
    <option value="Northern Samar" ></option>
    <option value="Nueva Ecija" ></option>
    <option value="Nueva Vizcaya" ></option>
    <option value="Occidental Mindoro" ></option>
    <option value="Oriental Mindoro" ></option>
    <option value="Palawan" ></option>
    <option value="Pampanga" ></option>
    <option value="Pangasinan" ></option>
    <option value="Quezon" ></option>
    <option value="Quirino" ></option>
    <option value="Rizal" ></option>
    <option value="Romblon" ></option>
    <option value="Samar" ></option>
    <option value="Sarangani" ></option>
    <option value="Siquijor" ></option>
    <option value="Sorsogon" ></option>
    <option value="South Cotabato" ></option>
    <option value="Southern Leyte" ></option>
    <option value="Sultan Kudarat" ></option>
    <option value="Sulu" ></option>
    <option value="Surigao del Norte" ></option>
    <option value="Surigao del Sur" ></option>
    <option value="Tarlac" ></option>
    <option value="Tawi-Tawi" ></option>
    <option value="Zambales" ></option>
    <option value="Zamboanga City" ></option>
    <option value="Zamboanga del Norte" ></option>
    <option value="Zamboanga del Sur" ></option>
    <option value="Zamboanga Sibugay" ></option>
</select>